training:
  learning_rate: 3e-4
  num_envs: 1
  num_steps: 2048
  total_timesteps: 1000000
  update_epochs: 1
  num_minibatches: 1
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  clip_vloss: True
  norm_adv: True
  vf_coef: 0.25
  ent_coef: 0.01
  max_grad_norm: 0.5
  decay_delta: 0.995
  max_kl: 0.01
  cg_damping: 0.1
  line_search_coef: 0.8
  max_backtracks: 10